import WebSocket from "ws";
import { Firestore, doc, setDoc, getDoc, getDocs, collection, query, where } from "firebase/firestore";

export interface DDSMonitoringParsedData {
  status?: string;
  initialMoney?: number;
  currentMoney?: number;
  totalProfit?: number;
  totalCycle?: number;
  scriptVersion?: string;
  timestamp?: string;
  rawText?: string;
}

export interface DiscordBotLog {
  id: string;
  timestamp: string;
  type: "INFO" | "SUCCESS" | "WARNING" | "ERROR";
  channelId?: string;
  channelName?: string;
  cloudName?: string;
  message: string;
  parsedData?: DDSMonitoringParsedData;
}

// Clean and convert Indonesian/Standard currency numbers: e.g. "Rp. 54.750.833" -> 54750833
export function parseCurrencyStringToNumber(str?: string): number | undefined {
  if (!str) return undefined;
  // Strip currency symbols, spaces, "+", "Rp", "RP", etc.
  const cleaned = str
    .replace(/[rR][pP]\.?/g, "")
    .replace(/\+/g, "")
    .replace(/\s+/g, "")
    .replace(/[^0-9.,-]/g, "")
    .trim();

  if (!cleaned) return undefined;

  // Indonesian dot format (54.750.833) vs comma format
  let numStr = cleaned;
  if (numStr.includes(".") && !numStr.includes(",")) {
    // e.g. "54.750.833" -> "54750833"
    numStr = numStr.replace(/\./g, "");
  } else if (numStr.includes(",") && !numStr.includes(".")) {
    // e.g. "54,750,833" -> "54750833"
    numStr = numStr.replace(/,/g, "");
  } else if (numStr.includes(".") && numStr.includes(",")) {
    // "54.750.833,00" -> "54750833"
    numStr = numStr.split(",")[0].replace(/\./g, "");
  }

  const num = Number(numStr);
  return isNaN(num) ? undefined : num;
}

// Parse Embed or Plain text generated by DDS Script
export function parseDDSEmbed(msgPayload: any): DDSMonitoringParsedData {
  const result: DDSMonitoringParsedData = {};
  const nowIso = new Date().toISOString();
  result.timestamp = nowIso;

  const embeds = Array.isArray(msgPayload.embeds) ? msgPayload.embeds : [];
  const content = typeof msgPayload.content === "string" ? msgPayload.content : "";

  let combinedText = content;

  // 1. Process Embeds
  for (const embed of embeds) {
    if (embed.title) combinedText += `\nTitle: ${embed.title}`;
    if (embed.description) combinedText += `\nDescription: ${embed.description}`;
    if (embed.footer?.text) combinedText += `\nFooter: ${embed.footer.text}`;
    if (embed.timestamp) result.timestamp = embed.timestamp;

    // Parse structured embed fields if present
    if (Array.isArray(embed.fields)) {
      for (const field of embed.fields) {
        const name = String(field.name || "").toLowerCase();
        const val = String(field.value || "").trim();

        if (name.includes("status")) {
          result.status = val.replace(/[`*]/g, "").replace(/^\[\s*[✓vV]\s*\]\s*/, "").trim();
        } else if (name.includes("uang awal") || name.includes("initial") || name.includes("start money")) {
          result.initialMoney = parseCurrencyStringToNumber(val);
        } else if (name.includes("uang sekarang") || name.includes("current money") || name.includes("saldo")) {
          result.currentMoney = parseCurrencyStringToNumber(val);
        } else if (name.includes("profit") || name.includes("keuntungan")) {
          result.totalProfit = parseCurrencyStringToNumber(val);
        } else if (name.includes("cycle") || name.includes("putaran")) {
          const cNum = parseInt(val.replace(/[^0-9]/g, ""), 10);
          if (!isNaN(cNum)) result.totalCycle = cNum;
        } else if (name.includes("versi") || name.includes("version") || name.includes("script")) {
          result.scriptVersion = val.replace(/[`*]/g, "").trim();
        }
      }
    }
  }

  result.rawText = combinedText;

  // 2. Regex fallback / enrichment across all combined text
  if (!result.status) {
    const statusMatch = combinedText.match(/Status\s*[:=]\s*[`*]?([^`*\n\r]+)/i);
    if (statusMatch && statusMatch[1]) {
      result.status = statusMatch[1].replace(/^\[\s*[✓vV]\s*\]\s*/, "").trim();
    }
  }

  if (result.initialMoney === undefined) {
    const initMatch = combinedText.match(/(?:Uang Awal|Initial Money|Start Money)\s*[:=]\s*[`*]?([^\n\r`*]+)/i);
    if (initMatch && initMatch[1]) {
      result.initialMoney = parseCurrencyStringToNumber(initMatch[1]);
    }
  }

  if (result.currentMoney === undefined) {
    const currMatch = combinedText.match(/(?:Uang Sekarang|Current Money|Saldo Sekarang|Live Saldo)\s*[:=]\s*[`*]?([^\n\r`*]+)/i);
    if (currMatch && currMatch[1]) {
      result.currentMoney = parseCurrencyStringToNumber(currMatch[1]);
    }
  }

  if (result.totalProfit === undefined) {
    const profitMatch = combinedText.match(/(?:Total Profit|Profit|Keuntungan)\s*[:=]\s*[`*]?([^\n\r`*]+)/i);
    if (profitMatch && profitMatch[1]) {
      result.totalProfit = parseCurrencyStringToNumber(profitMatch[1]);
    } else if (result.currentMoney !== undefined && result.initialMoney !== undefined) {
      result.totalProfit = result.currentMoney - result.initialMoney;
    }
  }

  if (result.totalCycle === undefined) {
    const cycleMatch = combinedText.match(/(?:Total Cycle|Cycle|Putaran)\s*[:=]\s*[`*]?([0-9]+)/i);
    if (cycleMatch && cycleMatch[1]) {
      result.totalCycle = parseInt(cycleMatch[1], 10);
    }
  }

  if (!result.scriptVersion) {
    const verMatch = combinedText.match(/(?:Versi Script|Script Version|Version)\s*[:=]\s*[`*]?([^`*\n\r]+)/i);
    if (verMatch && verMatch[1]) {
      result.scriptVersion = verMatch[1].trim();
    } else if (combinedText.includes("DDS Premium")) {
      result.scriptVersion = "DDS Premium Script";
    }
  }

  // 3. Direct JSON fields support (if payload has top-level properties)
  if (result.initialMoney === undefined) {
    const rawInit = msgPayload.initialMoney ?? msgPayload.initial_money ?? msgPayload.uangAwal ?? msgPayload.uang_awal ?? msgPayload.startMoney;
    if (rawInit !== undefined) result.initialMoney = typeof rawInit === 'number' ? rawInit : parseCurrencyStringToNumber(String(rawInit));
  }

  if (result.currentMoney === undefined) {
    const rawCurr = msgPayload.currentMoney ?? msgPayload.current_money ?? msgPayload.uangSekarang ?? msgPayload.uang_sekarang ?? msgPayload.saldo ?? msgPayload.liveSaldo;
    if (rawCurr !== undefined) result.currentMoney = typeof rawCurr === 'number' ? rawCurr : parseCurrencyStringToNumber(String(rawCurr));
  }

  if (result.totalProfit === undefined) {
    const rawProf = msgPayload.totalProfit ?? msgPayload.total_profit ?? msgPayload.profit ?? msgPayload.keuntungan;
    if (rawProf !== undefined) result.totalProfit = typeof rawProf === 'number' ? rawProf : parseCurrencyStringToNumber(String(rawProf));
    else if (result.currentMoney !== undefined && result.initialMoney !== undefined) {
      result.totalProfit = result.currentMoney - result.initialMoney;
    }
  }

  if (result.totalCycle === undefined) {
    const rawCyc = msgPayload.totalCycle ?? msgPayload.total_cycle ?? msgPayload.cycle ?? msgPayload.putaran;
    if (rawCyc !== undefined) result.totalCycle = typeof rawCyc === 'number' ? rawCyc : parseInt(String(rawCyc).replace(/[^0-9]/g, ''), 10);
  }

  if (!result.status) {
    const rawStat = msgPayload.status ?? msgPayload.monitoringStatus ?? msgPayload.monitoring_status;
    if (rawStat) result.status = String(rawStat).trim();
  }

  if (!result.scriptVersion) {
    const rawVer = msgPayload.scriptVersion ?? msgPayload.script_version ?? msgPayload.version ?? msgPayload.versi;
    if (rawVer) result.scriptVersion = String(rawVer).trim();
  }

  return result;
}

/**
 * 🚀 CUSTOM WEBHOOK INGESTION ENGINE (PENGGANTI BOT DISCORD & DUAL-SYNC FORWARDER)
 * Memproses payload dari DDS Script, mengekstrak data monitoring, menyimpan ke Firestore (Cloud & Order),
 * dan meneruskan (forward) ke Discord Webhook asli jika dikonfigurasi.
 */
export async function processCustomCloudWebhook(
  db: Firestore,
  cloudIdentifier: string,
  rawPayload: any
): Promise<{
  success: boolean;
  message: string;
  statusCode?: number;
  error?: string;
  cloudId?: string;
  cloudName?: string;
  assignedOrderId?: string;
  monitoringData?: any;
  forwardedToDiscord?: boolean;
}> {
  try {
    const cleanId = (cloudIdentifier || '').trim();
    const payload = rawPayload || {};

    // 1. Ekstraksi Data Monitoring Lengkap
    const parsed = parseDDSEmbed(payload);

    // 2. Pencarian Dokumen Cloud Target
    let targetCloudDoc: any = null;

    // A. Cek Direct ID
    if (cleanId) {
      const cSnap = await getDoc(doc(db, "clouds", cleanId));
      if (cSnap.exists()) {
        targetCloudDoc = { id: cSnap.id, ...cSnap.data() };
      }
    }

    // B. Cek via payload.cloudId jika belum ketemu
    if (!targetCloudDoc && (payload.cloudId || payload.cloud_id)) {
      const pId = String(payload.cloudId || payload.cloud_id).trim();
      const cSnap = await getDoc(doc(db, "clouds", pId));
      if (cSnap.exists()) {
        targetCloudDoc = { id: cSnap.id, ...cSnap.data() };
      }
    }

    // C. Cek Semua Dokumen Cloud (Pencarian Cerdas berdasarkan Nama / Slug / Webhook URL)
    if (!targetCloudDoc) {
      const allSnap = await getDocs(collection(db, "clouds"));
      const allClouds = allSnap.docs.map(d => ({ id: d.id, ...d.data() }));

      const queryNormalized = cleanId.toLowerCase().replace(/[^a-z0-9]/g, "");
      const payloadName = String(payload.cloudName || payload.name || "").toLowerCase().replace(/[^a-z0-9]/g, "");

      for (const c of allClouds as any[]) {
        const cId = String(c.id || "").toLowerCase();
        const cNameNorm = String(c.name || "").toLowerCase().replace(/[^a-z0-9]/g, "");
        const cDiscordChannel = String(c.discordChannelId || "").trim();
        const cWebhookUrl = String(c.discordWebhookUrl || "");

        // Match by ID, Normalized Name (e.g. "cloud01" === "cloud01" or "cloud-1" === "cloud-1")
        if (queryNormalized && (cId === cleanId.toLowerCase() || cNameNorm === queryNormalized || cNameNorm.includes(queryNormalized) || queryNormalized.includes(cNameNorm))) {
          targetCloudDoc = c;
          break;
        }

        if (payloadName && (cNameNorm === payloadName || cNameNorm.includes(payloadName))) {
          targetCloudDoc = c;
          break;
        }

        if (cleanId && cDiscordChannel === cleanId) {
          targetCloudDoc = c;
          break;
        }

        if (cleanId && cWebhookUrl.includes(cleanId)) {
          targetCloudDoc = c;
          break;
        }
      }
    }

    // D. Fallback Terakhir: Jika hanya ada 1 cloud atau ambil cloud pertama jika id kosong
    if (!targetCloudDoc && !cleanId) {
      const allSnap = await getDocs(collection(db, "clouds"));
      if (!allSnap.empty) {
        targetCloudDoc = { id: allSnap.docs[0].id, ...allSnap.docs[0].data() };
      }
    }

    if (!targetCloudDoc) {
      return {
        success: false,
        statusCode: 404,
        error: "Cloud Not Found",
        message: `Cloud dengan identifier "${cloudIdentifier}" tidak ditemukan di database.`
      };
    }

    const nowIso = new Date().toISOString();

    // 2.1 VALIDASI SKEMA DDS FARMING LOG
    // Validasi apakah payload memuat setidaknya salah satu data farming penting (uang sekarang, uang awal, profit, cycle, atau status terstruktur)
    const hasValidFinancialData = parsed.currentMoney !== undefined || parsed.initialMoney !== undefined || parsed.totalProfit !== undefined;
    const hasValidMonitoringData = hasValidFinancialData || (parsed.status && parsed.totalCycle !== undefined);

    if (!hasValidMonitoringData) {
      const errorDetail = `Format Log Script Tidak Valid pada [${targetCloudDoc.name}]! Pastikan script mengirimkan log profit farming DDS dengan benar.`;
      const rawPreview = typeof payload === 'string' ? payload : JSON.stringify(payload);

      // Catat status error pada dokumen Cloud di Firestore
      await setDoc(doc(db, "clouds", targetCloudDoc.id), {
        webhookStatus: "PAYLOAD_INVALID",
        lastErrorPayload: rawPreview.substring(0, 1000),
        lastErrorMessage: errorDetail,
        lastErrorTimestamp: nowIso,
        updatedAt: nowIso
      }, { merge: true });

      return {
        success: false,
        statusCode: 400,
        error: "Invalid DDS Log Schema",
        message: errorDetail,
        cloudId: targetCloudDoc.id,
        cloudName: targetCloudDoc.name
      };
    }

    // 3. Hitung & Resolusi Nilai Angka Presisi
    const numInit = parsed.initialMoney !== undefined ? parsed.initialMoney : targetCloudDoc.initialMoney;
    const numCurrent = parsed.currentMoney !== undefined ? parsed.currentMoney : targetCloudDoc.currentMoney;
    let calcProfit = parsed.totalProfit !== undefined ? parsed.totalProfit : targetCloudDoc.totalProfit;

    if (calcProfit === undefined && numCurrent !== undefined && numInit !== undefined) {
      calcProfit = numCurrent - numInit;
    }

    const effectiveStatus = parsed.status || targetCloudDoc.monitoringStatus || "Farming Office Aktif";
    const effectiveCycle = parsed.totalCycle !== undefined ? parsed.totalCycle : (targetCloudDoc.totalCycle || 0);
    const effectiveScriptVer = parsed.scriptVersion || targetCloudDoc.scriptVersion || "DDS Premium Script";
    const effectiveDiscordWebhook = (payload.discordWebhookUrl || targetCloudDoc.discordWebhookUrl || "").trim();

    const monitoringDataObj = {
      status: effectiveStatus,
      initialMoney: numInit || 0,
      currentMoney: numCurrent || 0,
      totalProfit: calcProfit || 0,
      totalCycle: effectiveCycle,
      scriptVersion: effectiveScriptVer,
      lastUpdated: nowIso,
      rawText: parsed.rawText || ''
    };

    // 4. Update Dokumen Cloud di Firestore (Reset webhookStatus to OK)
    const cloudUpdatePayload: any = {
      monitoringData: monitoringDataObj,
      monitoringStatus: effectiveStatus,
      webhookStatus: "OK",
      lastErrorPayload: null,
      lastErrorMessage: null,
      lastErrorTimestamp: null,
      status: "IN_USE",
      statusLabel: "TERPAKAI",
      lastWebhookUpdate: nowIso,
      updatedAt: nowIso
    };

    if (numInit !== undefined) cloudUpdatePayload.initialMoney = numInit;
    if (numCurrent !== undefined) cloudUpdatePayload.currentMoney = numCurrent;
    if (calcProfit !== undefined) cloudUpdatePayload.totalProfit = calcProfit;
    if (effectiveCycle !== undefined) cloudUpdatePayload.totalCycle = effectiveCycle;
    if (effectiveScriptVer) cloudUpdatePayload.scriptVersion = effectiveScriptVer;

    await setDoc(doc(db, "clouds", targetCloudDoc.id), cloudUpdatePayload, { merge: true });

    // 5. Sinkronisasi Realtime ke Orderan Terpasang (Khususnya currentMoney untuk Live Saldo Pelanggan)
    const assignedOrderId = payload.orderId || targetCloudDoc.assignedOrderId || targetCloudDoc.currentOrderId;
    if (assignedOrderId) {
      const orderUpdatePayload: any = {
        lastMonitoringUpdate: nowIso,
        updated: nowIso
      };
      if (numCurrent !== undefined) orderUpdatePayload.currentMoney = numCurrent;
      if (numInit !== undefined) orderUpdatePayload.initialMoney = numInit;
      if (calcProfit !== undefined) orderUpdatePayload.monitoringProfit = calcProfit;

      await setDoc(doc(db, "orders", assignedOrderId), orderUpdatePayload, { merge: true }).catch((err) => {
        console.warn("Sinkronisasi live saldo ke order error:", err);
      });
    }

    // 6. 🌐 FORWARD KE DISCORD ASLI (DUAL-SYNC FORWARDER)
    let forwardedToDiscord = false;
    if (effectiveDiscordWebhook && effectiveDiscordWebhook.startsWith("http")) {
      try {
        let discordPayloadToSend: any = null;

        // Jika payload yang masuk sudah berformat embed/discord webhook, teruskan langsung
        if (payload.embeds || payload.content) {
          discordPayloadToSend = payload;
        } else {
          // Format menjadi Embed Discord Resmi
          const formattedInit = numInit !== undefined ? `Rp. ${numInit.toLocaleString('id-ID')}` : '-';
          const formattedCurrent = numCurrent !== undefined ? `Rp. ${numCurrent.toLocaleString('id-ID')}` : '-';
          const formattedProfit = calcProfit !== undefined ? `+ Rp. ${calcProfit.toLocaleString('id-ID')}` : '-';

          discordPayloadToSend = {
            username: "Entong Cloud Monitor",
            avatar_url: "https://raw.githubusercontent.com/lucide-icons/lucide/main/icons/server.png",
            embeds: [
              {
                title: `🎮 DDS Premium Script — ${targetCloudDoc.name}`,
                description: `**Status**: \`[✓] ${effectiveStatus}\`\n**Order Terpasang**: #${assignedOrderId || 'Belum ada'}\n**Pelanggan**: ${targetCloudDoc.assignedCustomerName || '-'}\n**Roblox**: ${targetCloudDoc.assignedGameUsername || '-'}`,
                color: 65398, // #00E676 Emerald Green
                fields: [
                  { name: "💰 Uang Awal", value: formattedInit, inline: true },
                  { name: "💵 Uang Sekarang", value: formattedCurrent, inline: true },
                  { name: "📈 Total Profit", value: formattedProfit, inline: true },
                  { name: "🔄 Total Cycle", value: `${effectiveCycle}`, inline: true },
                  { name: "⚙️ Versi Script", value: effectiveScriptVer, inline: true },
                  { name: "🕒 Waktu Update", value: new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false }) + ' WIB', inline: true }
                ],
                footer: { text: "Entong Store Realtime Cloud Ingestion" },
                timestamp: nowIso
              }
            ]
          };
        }

        // Asynchronous non-blocking forward to Discord
        fetch(effectiveDiscordWebhook, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(discordPayloadToSend)
        }).then(res => {
          if (!res.ok) console.warn(`Discord forward status: ${res.status}`);
        }).catch(dErr => {
          console.warn("Dual-sync forward ke Discord gagal:", dErr);
        });

        forwardedToDiscord = true;
      } catch (fErr) {
        console.warn("Persiapan forward ke Discord gagal:", fErr);
      }
    }

    return {
      success: true,
      message: `Monitoring synced successfully to ${targetCloudDoc.name}`,
      cloudId: targetCloudDoc.id,
      cloudName: targetCloudDoc.name,
      assignedOrderId: assignedOrderId || undefined,
      monitoringData: monitoringDataObj,
      forwardedToDiscord
    };
  } catch (err: any) {
    return {
      success: false,
      message: `Internal processing error: ${err.message}`
    };
  }
}

export class DiscordBotListener {
  private ws: WebSocket | null = null;
  private token: string = "";
  private heartbeatTimer: NodeJS.Timeout | null = null;
  private reconnectTimer: NodeJS.Timeout | null = null;
  private isManualStop: boolean = false;
  private sequence: number | null = null;
  private db: Firestore;

  public status: "DISCONNECTED" | "CONNECTING" | "CONNECTED" | "ERROR" = "DISCONNECTED";
  public botUser: { id?: string; username?: string; discriminator?: string } | null = null;
  public logs: DiscordBotLog[] = [];
  public mappedChannelsCount: number = 0;
  public lastSyncTime: string | null = null;

  constructor(db: Firestore) {
    this.db = db;
  }

  public addLog(type: "INFO" | "SUCCESS" | "WARNING" | "ERROR", message: string, extra: Partial<DiscordBotLog> = {}) {
    const logItem: DiscordBotLog = {
      id: `log_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`,
      timestamp: new Date().toISOString(),
      type,
      message,
      ...extra
    };
    this.logs.unshift(logItem);
    if (this.logs.length > 100) this.logs.pop();
    console.log(`[DiscordBotListener] [${type}] ${message}`);
  }

  public async start(botToken?: string): Promise<{ success: boolean; message: string }> {
    const targetToken = (botToken || process.env.DISCORD_BOT_TOKEN || "").trim();
    if (!targetToken) {
      this.status = "DISCONNECTED";
      const msg = "DISCORD_BOT_TOKEN belum disetel. Masukkan token bot Discord.";
      this.addLog("WARNING", msg);
      return { success: false, message: msg };
    }

    this.token = targetToken;
    this.isManualStop = false;
    this.status = "CONNECTING";
    this.addLog("INFO", "Memulai koneksi ke Discord Gateway WebSocket...");

    this.connectGateway();
    return { success: true, message: "Koneksi Discord Gateway diinisiasi." };
  }

  public stop(): { success: boolean; message: string } {
    this.isManualStop = true;
    this.status = "DISCONNECTED";
    this.cleanup();
    this.addLog("INFO", "Discord Bot Gateway dihentikan manual oleh admin.");
    return { success: true, message: "Discord Bot Listener dihentikan." };
  }

  private cleanup() {
    if (this.heartbeatTimer) {
      clearInterval(this.heartbeatTimer);
      this.heartbeatTimer = null;
    }
    if (this.reconnectTimer) {
      clearTimeout(this.reconnectTimer);
      this.reconnectTimer = null;
    }
    if (this.ws) {
      try {
        this.ws.removeAllListeners();
        this.ws.close();
      } catch (e) {}
      this.ws = null;
    }
  }

  private connectGateway() {
    this.cleanup();
    if (this.isManualStop) return;

    try {
      const gatewayUrl = "wss://gateway.discord.gg/?v=10&encoding=json";
      this.ws = new WebSocket(gatewayUrl);

      this.ws.on("open", () => {
        this.addLog("INFO", "Koneksi socket terbuka, menunggu Opcode 10 HELLO...");
      });

      this.ws.on("message", async (rawData: WebSocket.RawData) => {
        try {
          const packet = JSON.parse(rawData.toString());
          await this.handleGatewayPacket(packet);
        } catch (err: any) {
          this.addLog("ERROR", `Gagal memproses paket gateway: ${err.message}`);
        }
      });

      this.ws.on("close", (code, reason) => {
        this.status = "DISCONNECTED";
        this.addLog("WARNING", `Socket terputus (Code: ${code}, Reason: ${reason.toString() || 'None'})`);
        if (!this.isManualStop) {
          this.reconnectTimer = setTimeout(() => {
            this.addLog("INFO", "Mencoba menghubungkan ulang ke Discord Gateway...");
            this.connectGateway();
          }, 6000);
        }
      });

      this.ws.on("error", (err) => {
        this.status = "ERROR";
        this.addLog("ERROR", `Socket Error: ${err.message}`);
      });
    } catch (err: any) {
      this.status = "ERROR";
      this.addLog("ERROR", `Gagal inisialisasi WebSocket: ${err.message}`);
    }
  }

  private async handleGatewayPacket(packet: { op: number; d: any; s: number | null; t: string | null }) {
    if (packet.s !== null) {
      this.sequence = packet.s;
    }

    // Opcode 10: HELLO -> Setup Heartbeat and Send IDENTIFY
    if (packet.op === 10) {
      const heartbeatInterval = packet.d.heartbeat_interval;
      this.startHeartbeat(heartbeatInterval);
      this.sendIdentify();
      return;
    }

    // Opcode 11: HEARTBEAT ACK
    if (packet.op === 11) {
      return;
    }

    // Opcode 0: DISPATCH
    if (packet.op === 0) {
      if (packet.t === "READY") {
        this.status = "CONNECTED";
        this.botUser = packet.d.user;
        const tag = `${this.botUser?.username}#${this.botUser?.discriminator || '0'}`;
        this.addLog("SUCCESS", `Discord Bot Siap & Aktif Memantau Channel: ${tag}`);
        return;
      }

      if (packet.t === "MESSAGE_CREATE") {
        await this.handleMessageCreate(packet.d);
      }
    }
  }

  private startHeartbeat(intervalMs: number) {
    if (this.heartbeatTimer) clearInterval(this.heartbeatTimer);
    this.heartbeatTimer = setInterval(() => {
      if (this.ws && this.ws.readyState === WebSocket.OPEN) {
        this.ws.send(JSON.stringify({ op: 1, d: this.sequence }));
      }
    }, intervalMs);
  }

  private sendIdentify() {
    if (!this.ws || this.ws.readyState !== WebSocket.OPEN) return;
    // Intents: GUILDS (1 << 0) | GUILD_MESSAGES (1 << 9) | MESSAGE_CONTENT (1 << 15) = 33281
    const identifyPayload = {
      op: 2,
      d: {
        token: this.token,
        intents: 33281,
        properties: {
          os: "linux",
          browser: "entong-cloud-monitor",
          device: "entong-bot"
        }
      }
    };
    this.ws.send(JSON.stringify(identifyPayload));
  }

  public async handleMessageCreate(message: any) {
    const channelId = String(message.channel_id || "");
    const embeds = Array.isArray(message.embeds) ? message.embeds : [];
    const content = String(message.content || "");

    // Quick filter: ignore messages that have neither content nor embeds
    if (!content && embeds.length === 0) return;

    // Check if this looks like a DDS Script message
    const isDDSContent = content.toLowerCase().includes("farming") ||
      content.toLowerCase().includes("uang") ||
      embeds.some(e => 
        (e.title || "").toLowerCase().includes("dds") || 
        (e.title || "").toLowerCase().includes("farming") ||
        (e.description || "").toLowerCase().includes("uang") ||
        (e.fields || []).some((f: any) => (f.name || "").toLowerCase().includes("uang") || (f.name || "").toLowerCase().includes("status"))
      );

    // Parse the monitoring payload
    const parsed = parseDDSEmbed(message);
    if (!parsed.status && parsed.currentMoney === undefined && !isDDSContent) {
      return;
    }

    this.addLog("INFO", `Menerima pesan DDS di channel [${channelId}]: Uang Sekarang = ${parsed.currentMoney ? 'Rp ' + parsed.currentMoney.toLocaleString('id-ID') : '-'}`, {
      channelId,
      parsedData: parsed
    });

    // Match this channel to Firestore Cloud Document
    await this.syncToFirestore(channelId, parsed);
  }

  public async syncToFirestore(channelId: string, parsed: DDSMonitoringParsedData, manualCloudId?: string): Promise<{ success: boolean; cloudName?: string; orderId?: string }> {
    try {
      let targetCloudDoc: any = null;

      // 1. Direct Cloud ID if provided manually
      if (manualCloudId) {
        const cSnap = await getDoc(doc(this.db, "clouds", manualCloudId));
        if (cSnap.exists()) {
          targetCloudDoc = { id: cSnap.id, ...cSnap.data() };
        }
      }

      // 2. Find by discordChannelId
      if (!targetCloudDoc && channelId) {
        const qChan = query(collection(this.db, "clouds"), where("discordChannelId", "==", channelId.trim()));
        const snapChan = await getDocs(qChan);
        if (!snapChan.empty) {
          targetCloudDoc = { id: snapChan.docs[0].id, ...snapChan.docs[0].data() };
        }
      }

      // 3. Fallback: Search all clouds by channel name or index (e.g. channel #cloud-1 -> "Cloud 01" / "Cloud 1")
      if (!targetCloudDoc) {
        const allCloudsSnap = await getDocs(collection(this.db, "clouds"));
        const allClouds = allCloudsSnap.docs.map(d => ({ id: d.id, ...d.data() }));

        for (const cloud of allClouds as any[]) {
          const cChan = String(cloud.discordChannelId || "").trim();
          const cName = String(cloud.name || "").toLowerCase().replace(/[^a-z0-9]/g, "");
          const cWebhook = String(cloud.discordWebhookUrl || "");

          if (cChan === channelId) {
            targetCloudDoc = cloud;
            break;
          }
          // If webhook url contains the channel ID
          if (channelId && cWebhook.includes(channelId)) {
            targetCloudDoc = cloud;
            break;
          }
        }
      }

      if (!targetCloudDoc) {
        this.addLog("WARNING", `Channel [${channelId}] belum dipetakan ke Cloud manapun. Tambahkan Channel ID ini pada kartu Cloud.`, {
          channelId,
          parsedData: parsed
        });
        return { success: false };
      }

      const nowIso = new Date().toISOString();
      const numInit = parsed.initialMoney !== undefined ? parsed.initialMoney : targetCloudDoc.initialMoney;
      const numCurrent = parsed.currentMoney !== undefined ? parsed.currentMoney : targetCloudDoc.currentMoney;
      let calcProfit = parsed.totalProfit !== undefined ? parsed.totalProfit : targetCloudDoc.totalProfit;

      if (calcProfit === undefined && numCurrent !== undefined && numInit !== undefined) {
        calcProfit = numCurrent - numInit;
      }

      const effectiveStatus = parsed.status || targetCloudDoc.monitoringStatus || "Farming Office Aktif";
      const effectiveCycle = parsed.totalCycle !== undefined ? parsed.totalCycle : (targetCloudDoc.totalCycle || 0);
      const effectiveScriptVer = parsed.scriptVersion || targetCloudDoc.scriptVersion || "DDS Premium Script";

      // Update Cloud in Firestore
      const cloudUpdate: any = {
        monitoringStatus: effectiveStatus,
        status: "IN_USE",
        statusLabel: "TERPAKAI",
        lastWebhookUpdate: nowIso,
        updatedAt: nowIso
      };

      if (numInit !== undefined) cloudUpdate.initialMoney = numInit;
      if (numCurrent !== undefined) cloudUpdate.currentMoney = numCurrent;
      if (calcProfit !== undefined) cloudUpdate.totalProfit = calcProfit;
      if (effectiveCycle !== undefined) cloudUpdate.totalCycle = effectiveCycle;
      if (effectiveScriptVer) cloudUpdate.scriptVersion = effectiveScriptVer;

      await setDoc(doc(this.db, "clouds", targetCloudDoc.id), cloudUpdate, { merge: true });

      // Synchronize to active assigned order
      const assignedOrderId = targetCloudDoc.assignedOrderId || targetCloudDoc.currentOrderId;
      if (assignedOrderId) {
        const orderUpdate: any = {
          lastMonitoringUpdate: nowIso,
          updated: nowIso
        };
        if (numCurrent !== undefined) orderUpdate.currentMoney = numCurrent;
        if (numInit !== undefined) orderUpdate.initialMoney = numInit;
        if (calcProfit !== undefined) orderUpdate.monitoringProfit = calcProfit;

        await setDoc(doc(this.db, "orders", assignedOrderId), orderUpdate, { merge: true }).catch((err) => {
          console.warn("Order sync warning:", err);
        });
      }

      this.lastSyncTime = nowIso;
      this.addLog("SUCCESS", `Berhasil sinkronkan data ke [${targetCloudDoc.name}] & Order [#${assignedOrderId || '-'}]`, {
        channelId,
        cloudName: targetCloudDoc.name,
        parsedData: parsed
      });

      return {
        success: true,
        cloudName: targetCloudDoc.name,
        orderId: assignedOrderId || undefined
      };
    } catch (err: any) {
      this.addLog("ERROR", `Gagal sinkronkan ke Firestore: ${err.message}`, { channelId });
      return { success: false };
    }
  }
}
